<?php


namespace app\components;


use app\models\Category;
use yii\base\Widget;

class MenuWidget extends Widget
{
	public $tpl;
	public $data; // data from database
	public $tree;
	public $menuHtml;

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub

		if ($this->tpl === null) {
			$this->tpl = 'menu';
		}
		$this->tpl .= '.php';
	}

	public function run(){
		$this->data = Category::find()->indexBy('id')->asArray()->all();
		$this->tree = $this->getTree();
		vardump($this->tree);
		return $this->tpl;
	}

	protected function getTree(){
		$tree = [];
		foreach ($this->data as $id=>&$node) {
			if (!$node['parent_id'])
				$tree[$id] = &$node;
			else
				$this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
		}
		return $tree;
	}
}